# Generated by Django 3.0.2 on 2021-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozaic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='output',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
